baseURL = "/"
languageCode = "en-US"
defaultContentLanguage = "en"

title = "Security Frameworks by David Rowe"
theme = "learn"
metaDataFormat = "yaml"
defaultContentLanguageInSubdir= true

[params]
  editURL = "https://github.com/davidprowe/secframe/edit/master/Site/content/"
  description = "AD and AWS Security Frameworks by David Rowe"
  author = "David Rowe"
  showVisitedLinks = true
  disableBreadcrumb = false
  disableNextPrev = false
  disableLandingPageButton = false
  disableMermaid = false
  customMermaidURL = "https://unpkg.com/mermaid@8.8.0/dist/mermaid.min.js"
  titleSeparator = "::"

[outputs]
home = [ "HTML", "RSS", "JSON"]

[[menu.shortcuts]]
name = "<i class='fab fa-fw fa-github'></i> GitHub repo"
identifier = "ds"
url = "https://github.com/davidprowe/secframe"
weight = 10


[[menu.shortcuts]]
name = "<i class='fas fa-fw fa-bullhorn'></i> Contact"
url = "/contact"
weight = 30
